### ISSUE TITLE
Disable image recognition if <2GB of RAM available

### ISSUE THREAD

**Issue by artifishvr** [artificialbutter/SpongeML#3]
Fixes complete freezing of my docker host

@butterroach PLEASE

**Comment by Butterroach** [comment]
might do this once I get back and finally have access to my pc

**Comment by Butterroach** [comment]
(which is today!!!)

**Comment by Butterroach** [comment]
Random pic for entertainment

![Uploading 20240418_183559.jpg …]()

(I gave up on uploading that GOD IT'S SO FUCKING COLD)

**Comment by Butterroach** [comment]
uh all methods i found either require an external dependency or are long and complicated as fuck pick one

**Comment by Butterroach** [comment]
(to get available ram)

**Comment by Butterroach** [comment]
too slow im picking the one with the external dependency

**Comment by artifishvr** [comment]
@Butterroach next time in PRs or commits somewhere can you say `Closes #3` or something [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) pleaseeeeee it would be so nice

**Comment by Butterroach** [comment]
no
