### ISSUE TITLE
Improve Action times/slim docker image

### ISSUE THREAD

**Issue by artifishvr** [artificialbutter/SpongeML#5]
Currently the docker builds take ~15 minutes to complete due to the massive size of torch. Should be improved plsssss (caching layers somehow, slimming torch somehow, or choosing a different base image)

**Comment by artifishvr** [comment]
@spongedsc/ai pls fix

**Comment by Butterroach** [comment]
no
![Screenshot_20240418_173501](https://github.com/spongedsc/SpongeML/assets/111113093/80ff4ecd-8fa9-47cc-9024-875606079e8a)

**Comment by artifishvr** [comment]
@spongedsc/web pls fix

**Comment by artifishvr** [comment]
fixed by aa86989

**Comment by Butterroach** [comment]
burger

**Comment by Butterroach** [comment]
i can reopen it
